blank_issues_enabled: false

contact_links:

  - name: Documentation
    url: https://jihoonahn.github.io/tuistui/main/documentation/tuistui/
    about: Read the TuistUI's documentation
  - name: Discord
    url: https://discord.com/users/649233319820787712
    about: discord chat
